sudo: false
language: python
python:
- '3.6'
install: pip install tox-travis codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: ehO43pIlxbZkHl12CTQIWwpSEfeHOyHq4OcV60GOm0n4s0BodxfP/nFVU44q2nFt3lLwgQIQQpKJoullYERe/mutETK+y19+6MK811Qp9m5QEgMwy3cLikoE9mSQXdp9S08ENVHA4/BA0w1nsN//vTFrn4khmqpCOWj2J/SQT22sgh23mxsiFqaSxA3j5CBt7Vsda8TIirFkwLNs79ZrvuA7GRmhGs9ctOKxIl8QHnep8iOZTYLaWMBB5TERH9W/u+uYNZNvmkXnVmiQvXClHzmGz3Vrzi+DBwnBwRhrtkCBSAw97vZ5U9qqGBjxlz1DyOl6JRiHl7ZAfG3RXMHt6ExWlo89j+IhNTaeJybLMbR6TUxwYOzK1fDubAEEfQj53z20oGgFnVJl1whMtpqmD5HEowFnFcxcuoIBeJBvJzSxovcItUUWIWqzjebQ+4+y9kb6mzTKWdR81aQW6sh37LG+zMyd3ongRGsQi+q96qY51RwLdecC40q5azebLqwY7nf4K28aybCoIuZL93q7/j0STPabUoW01/qeOLe5tJKxTB8UpaAY/JjePzmMG7wxXUecNGwS9c3djHBo6SWZreeuzvMdOFzOusTwvpPueYU+7Eye4FnIXimk5jWLwBOuSPHLdhU8pJ/6zfUpWgf7uiEDPwPAEwKiTUux9RoJ+s4=
